class C1964jsRsp
  "use strict"

  constructor: ->
 #   instruction = [special, stateimm, j, jal, beq, bne, blez, bgtz, addi, addiu, slti, sltiu, andi, ori, xori, lui, cop0, reserved, cop2, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, lb, lh, reserved, lw, lbu, lhu, reserved, reserved, sb, sh, reserved, sw, reserved, reserved, reserved, reserved, reserved, reserved, lwc2, reserved, reserved, reserved, reserved, reserved, reserved, reserved, swc2, reserved, reserved, reserved, reserved, reserved]
 #   special = [sll, reserved, srl, sra, sllv, reserved, srlv, srav, jr, jalr, reserved, reserved, reserved, _break, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, add, addu, sub, subu, _and, _or, xor, nor, reserved, reserved, slt, sltu, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved]
 #   regimm = [bltz, bgez, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, bltzal, bgezal, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved]
 #   cop0 = [mf, reserved, reserved, reserved, mt, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved]
 #   cop2 = [mf, reserved, cf, reserved, mt, reserved, ct, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, vectop, vectop, vectop, vectop, vectop, vectop, vectop, vectop, vectop, vectop, vectop, vectop, vectop, vectop, vectop, vectop]
 #   vectop = [vmulf, vmulu, vrndp, vmulq, vmudl, vmudm, vmudn, vmudh, vmacf, vmacu, vrndn, vmacq, vmadl, vmadm, vmadn, vmadh, vadd, vsub, reserved, vabs, vaddc, vsubc, reserved, reserved, reserved, reserved, reserved, reserved, reserved, vsaw, reserved, reserved, vlt, veq, vne, vge, vcl, vch, vcr, vmrg, vand, vnand, vor, vnor, vxor, vnxor, reserved, reserved, vrcp, vrcpl, vrcph, vmov, vrsq, vrsql, vrsqh, vnoop, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved]
 #   lwc2 = [lbv, lsv, llv, ldv, lqv, lrv, lpv, luv, lhv, lfv, lwv, ltv, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved]
 #   swc2 = [sbv, ssv, slv, sdv, sqv, srv, spv, suv, shv, sfv, swv, stv, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved, reserved]

#hack global space until we export classes properly
#node.js uses exports; browser uses this (window)
root = exports ? this
root.C1964jsRsp = C1964jsRsp